GET https://tasks-mastered-backend.herokuapp.com/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY4NDQ1NDU2NH0.UnfnQWK6NajWaAR4CbBuWdlHa5Eai_luWs84sQbcwWg

###

POST https://tasks-mastered-backend.herokuapp.com/login
Content-Type: application/json

{
    "username": "Alex"
}

